doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB__URL)%'
            options: {}
    default_database: '%env(MONGODB__DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App\Core:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Core/Document'
                    prefix: App\Core\Document\