services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Core\:
        resource: '../../src/Core'
        exclude: '../../src/Core/{Document,Repository,Event}'

    # repositories
    App\Core\Repository\SnapshotRepository:
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - App\Core\Document\Snapshot

    App\Core\Repository\DefinitionRepository:
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - App\Core\Document\Definition

    App\Core\Repository\ProjectRepository:
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - App\Core\Document\Project

    # event subscribers
    App\Core\EventSubscriber\:
        resource: '../../src/Core/EventSubscriber'
        tags:
            - { name: kernel.event_subscriber }