services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Metrics\TechMetrics\:
        resource: '../../src/Metrics/TechMetrics'
        exclude: '../../src/Metrics/TechMetrics/{Document,Repository,Event}'

    # calculators
    App\Metrics\TechMetrics\Calculator\:
        resource: '../../src/Metrics/TechMetrics/Calculator'
        tags:
            - { name: calculator }