version: '3'
services:
    ##
    api:
        tty: true
        privileged: true
        stdin_open: true
        env_file:
            - ../envs/default.env
        links:
            - mongo

    ##
    mongo:
        image: mongo:latest
        tty: true
        privileged: true
        stdin_open: true
        env_file:
            - ../envs/default.env